### ISSUE TITLE
TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by rao208** [prasunroy/cnn-on-degraded-images#1]
Hello,

When I try to run train_deepcnn.py script I get this error:

> Traceback (most recent call last):
>   File "train_deepcnn.py", line 349, in <module>
>     train()
>   File "train_deepcnn.py", line 339, in train
>     initial_epoch=0)
>   File "/home/raov/.virtualenvs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
>     use_multiprocessing=use_multiprocessing)
>   File "/home/raov/.virtualenvs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 397, in fit
>     prefix='val_')
>   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/home/raov/.virtualenvs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 771, in on_epoch
>     self.callbacks.on_epoch_end(epoch, epoch_logs)
>   File "/home/raov/.virtualenvs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 302, in on_epoch_end
>     callback.on_epoch_end(epoch, logs)
>   File "/home/raov/.virtualenvs/deep_learning/lib/python3.6/site-packages/mlutils-0.1.0-py3.6.egg/mlutils/callbacks.py", line 70, in on_epoch_end
>   File "/home/raov/.virtualenvs/deep_learning/lib/python3.6/site-packages/mlutils-0.1.0-py3.6.egg/mlutils/callbacks.py", line 93, in _checkpoint
> TypeError: unsupported format string passed to NoneType.__format__
> 2020-04-14 01:39:24.486882: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
> 

I have NVIDIA GeForce GTX 1060 6 GB graphic card and I am using TensorFlow 2.1.0. CUDA and CUDNN are installed as given in the link:

https://www.tensorflow.org/install/gpu

I tried to search on Google, but couldn't find the solution for this. I found a similar error on StackOverflow (https://stackoverflow.com/questions/60000573/error-occurred-when-finalizing-generatordataset-iterator-cancelled-operation-w), but the accepted solution doesn't work for me. I believe that I have compatible CUDA and TensorFlow versions.

Please help!

**Comment by prasunroy** [comment]
It appears that latest versions of tensorflow and keras are not fully compatible with the code. I am able to get it working by downgrading tensorflow to version 1.15.0 and few minor tweaks in `train_deepcnn.py`.

***I would highly recommend you to use `conda` as package manager which will make installing dependencies sigficantly easy.***

1. Download and install either `Miniconda` or `Anaconda` from [here](https://docs.conda.io).

2. Update and configure `conda`.
```bash
conda update conda
conda config --set env_prompt "({name}) "
```

3. Create an environment and install dependencies. I assume name of the environment as `test`.
```bash
conda create -n test python pip numpy scipy pandas matplotlib pillow tensorflow-gpu=1.15 keras
```

4. Activate the environment and install additional dependencies.
```bash
conda activate test
pip install opencv-python
pip install git+https://github.com/prasunroy/mlutils.git
```

5. Change directory to repository root and make the following changes in `train_deepcnn.py`.
`line 252`: change `val_acc` to `val_accuracy`
`line 253`: change `val_acc` to `val_accuracy`
`line 255`: change `val_acc` to `val_accuracy`
`line 275`: change `acc` to `accuracy`
`line 276`: change `val_acc` to `val_accuracy`

6. If everything works properly you should be able to start training.
```bash
python train_deepcnn.py
```
